---
title: "CLIF Adult Pilot Data Analysis"
author: "Nensi Gjata and Shari Liu"
date: "10/5/2019"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

# Load, Import, and Organize Data
```{r load}
library(tidyverse)
library(dplyr)
library(cowplot)
library(lme4)
library(lmerTest)
library(ggplot2)

knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

setwd("~/Desktop/Nensi/Thesis/Analysis Datasets")
```

```{r import.data}
# import deidentified dataset
data <- read.csv(file="CLIF-Adult-Pilot-Dataset.csv") %>% 
  mutate(ID=as.factor(ID))
```

## Task 2: Tidy Data
```{r exp2.pilot}
exp2.adult.pilot <- data %>%
  select(ID, Version, contains("Exp2.Test")) %>% # select Task 2 trials, ID, and Version
  gather(orig, DV_Direction, contains("Exp2.Test")) %>% # split trials into rows
  separate(orig, c("IV_Depth","Exp", "Test"), sep = "([\\_\\.])", extra = "drop") %>% # separate trial number
  mutate(IV_Depth = as.numeric(sub("X","", IV_Depth)), IV_Obj_Depth_Diff = IV_Depth - 4, Test = as.character(sub("Test","", Test)), DV_Direction = ifelse(Test %in% "B", 100 - as.numeric(DV_Direction), as.numeric(DV_Direction))) %>%  # find depth, adjust for different versions
  na.omit() %>% #delete empty cells
  arrange(ID) # arrange by ID number
```

## Task 2: Plots
```{r exp2.pilot.plot}
# produce Task 2 plot
(exp2.plot <- exp2.adult.pilot %>% 
  ggplot(aes(x = IV_Obj_Depth_Diff, y= DV_Direction)) +
  scale_x_continuous(breaks=seq(-3,3,1)) +
  geom_line(aes(group=ID), color=rgb(0,0,0), alpha=0.1, size=.8) +
  geom_boxplot(aes(group=IV_Obj_Depth_Diff), color="#333333", width=.5, fill=NA, size=1) +
  geom_point(color="#5F8DAE", size=3) +
  stat_summary(fun.data="mean_cl_boot", geom="errorbar", color="#003e67", width=0.2, size=1.5) +
  stat_summary(fun="mean", geom="point", shape=23, size=4, fill="white", color="#003e67", stroke=2) +
  theme_bw() +
  theme(axis.text=element_text(size=23)) +
  labs(x = "", y = "") +
  coord_flip() )

ggsave(filename="pilot.task2.adult.plot.png", path="/Users/Nensi/Desktop", width = 30, height = 21, units = "cm", dpi=300)
```

## Task 3: Tidy Data
```{r exp3.pilot}
exp3.adult.pilot <- data %>%
  select(ID, Version, contains("Exp3.Test")) %>% # select Task 3 trials, ID, and Version
  gather(orig, DV_Preference, contains("Exp3.Test")) %>% # split trials into rows
  separate(orig, c("IV_Depth_Accept","Exp", "Test"), sep = "([\\_\\.])", extra = "drop") %>% # separate trial number
  mutate(Test = as.character(sub("Test","", Test)), IV_Depth_Accept = as.numeric(sub("X","", IV_Depth_Accept)), DV_Preference = ifelse((Version %in% "2" | Version %in% "4"), 100 - as.numeric(DV_Preference), as.numeric(DV_Preference))) %>% # find depth, adjust for different versions
  na.omit() %>% #delete empty cells
  arrange(ID) # arrange by ID number
```

## Task 3: Plots
```{r exp3.pilot.plot}
(exp3.plot <- exp3.adult.pilot %>% 
  ggplot(aes(x = IV_Depth_Accept, y = DV_Preference)) +
  scale_x_continuous(breaks=seq(1,6,1)) +
  geom_line(aes(group=ID), color=rgb(0,0,0), alpha=0.1, size=.8) +
  geom_boxplot(aes(group=IV_Depth_Accept), color="#333333", width=.4, fill=NA, size=1) +
  geom_point(color="#5F8DAE", size=3) +
  stat_summary(fun.data="mean_cl_boot", geom="errorbar", color="#003e67", width=0.15, size=1.5) +
  stat_summary(fun="mean", geom="point", shape=23, size=4, fill="white", color="#003e67", stroke=2) +
  theme_bw() +
  theme(axis.text=element_text(size=23)) +
  labs(x = "", y = ""))

ggsave(filename="pilot.task3.adult.plot.png", path="/Users/Nensi/Desktop", width = 30, height = 21, units = "cm", dpi=300)
```

## Task 4: Tidy Data
```{r exp4.pilot}
exp4.adult.pilot <- data %>%
  select(ID, Version, contains("Exp4.Test")) %>% # select Task 4 trials, ID, and Version
  gather(orig, DV_Depth, contains("Exp4.Test")) %>% # split trials into rows
  separate(orig, c("IV_Preference","Exp", "Test"), sep = "([\\_\\.])", extra = "drop") %>% # separate trial number
  mutate(IV_Preference = as.numeric(sub("X","", IV_Preference)), Test = as.character(sub("Test","", Test)), DV_Depth = ifelse((Version %in% "2" | Version %in% "4"), 100 - as.numeric(DV_Depth), as.numeric(DV_Depth))) %>% # find preference, adjust for different versions
  na.omit() %>% #delete empty cells
  arrange(ID) # arrange by ID number

```

## Task 4: Plots
```{r exp4.pilot.plot}
(exp4.plot <- exp4.adult.pilot %>% 
  ggplot(aes(x = IV_Preference, y = DV_Depth)) +
  scale_x_continuous(breaks=seq(1,7,1)) +
  geom_line(aes(group=ID), color=rgb(0,0,0), alpha=0.1, size=.8) +
  geom_boxplot(aes(group=IV_Preference), color="#333333", width=.5, fill=NA, size=1) +
  geom_point(color="#5F8DAE", size=3) +
  stat_summary(fun.data="mean_cl_boot", geom="errorbar", color="#003e67", width=0.15, size=1.5) +
  stat_summary(fun="mean", geom="point", shape=23, size=4, fill="white", color="#003e67", stroke=2) +
  theme_bw() +
  theme(axis.text=element_text(size=23)) +
  labs(x = "", y = ""))

ggsave(filename="pilot.task4.adult.plot.png", path="/Users/Nensi/Desktop", width = 30, height = 20, units = "cm", dpi=300)
```
